### ISSUE TITLE
ModuleNotFoundError: No module named 'openspeech.data.text'

### ISSUE THREAD

**Issue by harisgulzar1** [openspeech-team/openspeech#119]
# ❓ Questions & Help

I am trying to train the conformer model after cloning to the repository and installing everything in my docker environment.
Command:
```
root@c2a6f3ff9df5:/workspace/openspeech# python ./openspeech_cli/hydra_train.py \
> dataset=librispeech \
> dataset.dataset_download=False \
> dataset.dataset_path=/openspeech/train/LibriSpeech \
> dataset.manifest_file_path=/openspeech/train/libri_subword_manifest.txt \
> tokenizer=libri_subword \
> model=conformer_transducer \
> audio=fbank \lr_scheduler=warmup_reduce_lr_on_plateau \
> trainer=gpu \
> criterion=cross_entropy
```
But it gives me following error:
`ModuleNotFoundError: No module named 'openspeech.data.text'`
Any help on this will be appreciated. Thanks.

## Details
The complete log is as follows:
```
Traceback (most recent call last):
  File "./openspeech_cli/hydra_train.py", line 30, in <module>
    from openspeech.tokenizers import TOKENIZER_REGISTRY
  File "/opt/conda/lib/python3.8/site-packages/openspeech/__init__.py", line 23, in <module>
    import openspeech.criterion
  File "/opt/conda/lib/python3.8/site-packages/openspeech/criterion/__init__.py", line 76, in <module>
    module = importlib.import_module(f"openspeech.criterion.{criterion_name}")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/openspeech/criterion/__init__.py", line 70, in <module>
    module = importlib.import_module(f"openspeech.criterion.{file}.{python_file}")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/openspeech/criterion/cross_entropy/cross_entropy.py", line 29, in <module>
    from ...tokenizers.tokenizer import Tokenizer
  File "/opt/conda/lib/python3.8/site-packages/openspeech/tokenizers/__init__.py", line 75, in <module>
    module = importlib.import_module(f"openspeech.tokenizers.{vocab_name}")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/openspeech/tokenizers/__init__.py", line 69, in <module>
    module = importlib.import_module(f"openspeech.tokenizers.{file}.{tokenizer_name}")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/openspeech/tokenizers/librispeech/subword.py", line 28, in <module>
    from openspeech.datasets.librispeech.preprocess.subword import SENTENCEPIECE_MODEL_NAME
  File "/opt/conda/lib/python3.8/site-packages/openspeech/datasets/__init__.py", line 60, in <module>
    module = importlib.import_module(f"openspeech.datasets.{file}.{data_module_name}")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/openspeech/datasets/language_model/lit_data_module.py", line 31, in <module>
    from openspeech.data.text.data_loader import TextDataLoader
ModuleNotFoundError: No module named 'openspeech.data.text'
```

**Comment by Jeff-LiangF** [comment]
Same question here, did you get the solution yet?

**Comment by Jeff-LiangF** [comment]
I just build it from source via `pip install -e .`, now it works.

**Comment by sooftware** [comment]
How about `python3 -m pip install -e .`?   
I think the module is not properly installed.
