### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate * GiB

### ISSUE THREAD

**Issue by rkskekzzz** [openspeech-team/openspeech#155]
# ❓ Questions & Help
안녕하세요!
다른 model은 문제없이 학습을 진행하는데 rnn_transducer의 경우 메모리가 터집니다..ㅜㅜ

**학습환경** : Google Colab Pro +
**런타임** : Gpu (15.90 GiB ram)
**batch_size** : 1

**진행현황**
```
# 60까지 진행한 상태에서 out of memory 발생
Epoch 0:   0% 60/1230545 [00:13<74:34:47,  4.58it/s, loss=3.45e+03, v_num=hup1, train_loss=8.62e+3, learning_rate=1.48e-6]
```

### 실행 스크립트
```
!python ./openspeech_cli/hydra_train.py \
              dataset=ksponspeech \
              dataset.dataset_path=$my_dataset_path \
              dataset.manifest_file_path=$my_manifest_file_path \
              dataset.test_dataset_path=$my_test_dataset_path \
              dataset.test_manifest_dir=$my_test_manifest_file_dir \
              tokenizer=kspon_character model=rnn_transducer audio=melspectrogram \
              lr_scheduler=warmup_reduce_lr_on_plateau \
              trainer=gpu \
              criterion=transducer
```

### 전체 실행 결과
전체 코드는 아래 토글에 첨부하였습니다!

<details>
<summary> 눌러서 코드 열어보기 - Click to open code (Preset) </summary>

```text
Global seed set to 1
[2022-04-27 07:28:38,438][openspeech.utils][INFO] - audio:
  name: melspectrogram
  sample_rate: 16000
  frame_length: 20.0
  frame_shift: 10.0
  del_silence: false
  num_mels: 80
  apply_spec_augment: true
  apply_noise_augment: false
  apply_time_stretch_augment: false
  apply_joining_augment: false
augment:
  apply_spec_augment: false
  apply_noise_augment: false
  apply_joining_augment: false
  apply_time_stretch_augment: false
  freq_mask_para: 27
  freq_mask_num: 2
  time_mask_num: 4
  noise_dataset_dir: None
  noise_level: 0.7
  time_stretch_min_rate: 0.7
  time_stretch_max_rate: 1.4
dataset:
  dataset: ksponspeech
  dataset_path: /content/drive/MyDrive/kodata/groups
  test_dataset_path: /content/drive/MyDrive/kodata/groups
  manifest_file_path: /content/drive/MyDrive/kodata/manifest.txt
  test_manifest_dir: /content/drive/MyDrive/kodata/
  preprocess_mode: phonetic
criterion:
  criterion_name: transducer
  reduction: mean
  gather: true
lr_scheduler:
  lr: 0.0001
  scheduler_name: warmup_reduce_lr_on_plateau
  lr_patience: 1
  lr_factor: 0.3
  peak_lr: 0.0001
  init_lr: 1.0e-10
  warmup_steps: 4000
model:
  model_name: rnn_transducer
  encoder_hidden_state_dim: 320
  decoder_hidden_state_dim: 512
  num_encoder_layers: 4
  num_decoder_layers: 1
  encoder_dropout_p: 0.2
  decoder_dropout_p: 0.2
  bidirectional: true
  rnn_type: lstm
  output_dim: 512
  optimizer: adam
trainer:
  seed: 1
  accelerator: dp
  accumulate_grad_batches: 1
  num_workers: 4
  batch_size: 1
  check_val_every_n_epoch: 1
  gradient_clip_val: 5.0
  logger: wandb
  max_epochs: 20
  save_checkpoint_n_steps: 10000
  auto_scale_batch_size: binsearch
  sampler: else
  name: gpu
  device: gpu
  use_cuda: true
  auto_select_gpus: true
tokenizer:
  sos_token: <sos>
  eos_token: <eos>
  pad_token: <pad>
  blank_token: <blank>
  encoding: utf-8
  unit: kspon_character
  vocab_path: ../../../aihub_labels.csv
```

</details>

<details>
<summary> 눌러서 코드 열어보기 - Click to open code (Error) </summary>

```text
[2022-04-27 07:28:38,465][openspeech.utils][INFO] - Operating System : Linux 5.4.144+
[2022-04-27 07:28:38,465][openspeech.utils][INFO] - Processor : x86_64
[2022-04-27 07:28:38,467][openspeech.utils][INFO] - device : Tesla P100-PCIE-16GB
[2022-04-27 07:28:38,468][openspeech.utils][INFO] - CUDA is available : True
[2022-04-27 07:28:38,468][openspeech.utils][INFO] - CUDA version : 11.3
[2022-04-27 07:28:38,468][openspeech.utils][INFO] - PyTorch version : 1.11.0+cu113
wandb: Currently logged in as: sushin (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.15
wandb: Run data is saved locally in /content/drive/MyDrive/project/openspeech_fork/outputs/2022-04-27/07-28-38/wandb/run-20220427_072839-1jcbhup1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run elated-rain-13
wandb: ⭐️ View project at ****
wandb: 🚀 View run at ****
1228000 ,  1228000
2545 ,  2545
6000 ,  6000
[2022-04-27 07:28:49,467][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmp1uffgdrb
[2022-04-27 07:28:49,467][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmp1uffgdrb/_remote_module_non_sriptable.py
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py:65: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:293: LightningDeprecationWarning: Passing `Trainer(accelerator='dp')` has been deprecated in v1.5 and will be removed in v1.7. Use `Trainer(strategy='dp')` instead.
  f"Passing `Trainer(accelerator={accelerator!r})` has been deprecated"
Auto select gpus: [0]
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/configuration_validator.py:377: LightningDeprecationWarning: The `Callback.on_batch_end` hook was deprecated in v1.6 and will be removed in v1.8. Please use `Callback.on_train_batch_end` instead.
  f"The `Callback.{hook}` hook was deprecated in v1.6 and"
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type                 | Params
---------------------------------------------------
0 | criterion | TransducerLoss       | 0     
1 | fc        | Sequential           | 3.1 M 
2 | encoder   | RNNTransducerEncoder | 8.7 M 
3 | decoder   | RNNTransducerDecoder | 3.4 M 
---------------------------------------------------
15.2 M    Trainable params
0         Non-trainable params
15.2 M    Total params
60.932    Total estimated model params size (MB)
Epoch 0:   0% 60/1230545 [00:13<74:34:47,  4.58it/s, loss=3.45e+03, v_num=hup1, train_loss=8.62e+3, learning_rate=1.48e-6]
Error executing job with overrides: ['dataset=ksponspeech', ... ]

Traceback (most recent call last):
  File "./openspeech_cli/hydra_train.py", line 54, in hydra_main
    trainer.fit(model, data_module)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 207, in advance
    self.optimizer_idx,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    using_lbfgs=is_lbfgs,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 1625, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/adam.py", line 100, in step
    loss = closure()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/dp.py", line 125, in training_step
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/data_parallel.py", line 64, in forward
    output = super().forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/content/drive/MyDrive/project/openspeech_fork/openspeech/models/openspeech_transducer_model.py", line 227, in training_step
    logits = self.joint(encoder_outputs, decoder_outputs)
  File "/content/drive/MyDrive/project/openspeech_fork/openspeech/models/openspeech_transducer_model.py", line 141, in joint
    outputs = self.fc(outputs).log_softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 4.87 GiB (GPU 0; 15.90 GiB total capacity; 12.76 GiB already allocated; 2.03 GiB free; 12.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:               epoch ▁
wandb:       learning_rate ▁
wandb:             lr-Adam ▁
wandb:          train_loss ▁
wandb: trainer/global_step ▁▁
wandb: 
wandb: Run summary:
wandb:               epoch 0
wandb:       learning_rate 0.0
wandb:             lr-Adam 0.0
wandb:          train_loss 5459.3374
wandb: trainer/global_step 49
wandb: 
wandb: Synced elated-rain-13: https://wandb.ai/sushin/rnn_transducer-ksponspeech/runs/1jcbhup1
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220427_072839-1jcbhup1/logs
Epoch 0:   0% 60/1230545 [00:22<129:17:59,  2.64it/s, loss=3.45e+03, v_num=hup1, train_loss=8.62e+3, learning_rate=1.48e-6]
```

</details>

**Comment by upskyy** [comment]
@rkskekzzz 안녕하세요!
transducer 모델의 경우 memory를 많이 잡아먹어서 OOM이 발생하는 것 같은데요. ksponspeech에서 긴 문장들을 제거하고 학습하는 것도 하나의 방법일 것 같습니다.

**Comment by rkskekzzz** [comment]
감사합니다ㅃ 문장 길이 별로 파일을 나눠서 테스트 해보고 결과 확인해보겠습니다!
