### ISSUE TITLE
Using OpenSpeech With Self Downloaded Data

### ISSUE THREAD

**Issue by lianaling** [openspeech-team/openspeech#175]
# ❓ Questions & Help
Hi there, thank you for your contribution to ASR!

I'm rather new to this framework and encountered some issues.

I have previously downloaded `train-clean-100` and `dev-clean` from the `LibriSpeech` dataset and would like to use this version in `OpeenSpeech`, so I specified `dataset.dataset_download=False`. However there seems to be an error finding the path.

## Details

My script is as follows:

```sh
DATASET_PATH="..\data\LibriSpeech\train-clean-100"
MANIFEST_FILE_PATH="..\data\manifests\train-clean-100-proc.csv"

python ../openspeech/openspeech_cli/hydra_train.py \
    dataset=librispeech \
    dataset.dataset_download=False \
    dataset.dataset_path=$DATASET_PATH \
    dataset.manifest_file_path=$MANIFEST_FILE_PATH \
    tokenizer=libri_subword \
    model=conformer_lstm \
    audio=fbank \
    lr_scheduler=warmup_reduce_lr_on_plateau \
    trainer=cpu \
    criterion=cross_entropy
```

The error that I get:
```sh
[2022-07-06 20:30:57,482][openspeech.utils][INFO] - Operating System : Windows 10
[2022-07-06 20:30:57,483][openspeech.utils][INFO] - Processor : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
[2022-07-06 20:30:57,561][openspeech.utils][INFO] - CUDA is available : True
[2022-07-06 20:30:57,562][openspeech.utils][INFO] - PyTorch version : 1.9.0+cu111
[2022-07-06 20:30:57,565][openspeech.datasets.librispeech.lit_data_module][INFO] - Manifest file is not exists !!
Generate manifest files..
Error executing job with overrides: ['dataset=librispeech', 'dataset.dataset_download=False', 'dataset.dataset_path=..\\data\\LibriSpeech\\train-clean-100', 'dataset.manifest_file_path=..\\data\\manifests\\train-clean-100-proc.csv', 'tokenizer=libri_subword', 'model=conformer_lstm', 'audio=fbank', 'lr_scheduler=warmup_reduce_lr_on_plateau', 'trainer=cpu', 'criterion=cross_entropy']
Traceback (most recent call last):
  File "../openspeech/openspeech_cli/hydra_train.py", line 44, in hydra_main
    data_module.prepare_data()
  File "C:\Users\liana\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\core\datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "c:\users\liana\documents\projects\openspeech\openspeech\datasets\librispeech\lit_data_module.py", line 148, in prepare_data     
    generate_manifest_files(
  File "c:\users\liana\documents\projects\openspeech\openspeech\datasets\librispeech\preprocess\subword.py", line 64, in generate_manifest_files
    transcripts_collection = collect_transcripts(dataset_path)
  File "c:\users\liana\documents\projects\openspeech\openspeech\datasets\librispeech\preprocess\preprocess.py", line 41, in collect_transcripts
    for subfolder1 in os.listdir(os.path.join(dataset_path, dataset)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '..\\data\\LibriSpeech\\train-clean-100\\train-960'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I'm sure that the path directory exists, but it's returning me path not found error. I'm not sure where the `train-960` comes from, as I only specified `..\data\LibriSpeech\train-clean-100` as my dataset path.

Also, I would like to ask if there's a script to generate manifest files, or is this script only available when `dataset.dataset_download=True`. Do I need to manually generate manifest files since I didn't download it through your API?

I've been trying to get this work for the entire day to no avail. Any help would be greatly appreciated!

**Comment by lianaling** [comment]
I solved this newbie issue by inspecting the code under `openspeech/datasets` , `openspeech/data` and `openspeech-cli/`. Since my use case was specific, I had to tweak the code to match my target directory, number of training/validation/testing data, modify the `LIBRISPEECH_PARTS` to only contain the few specific LibriSpeech folders that I wanted to download. Also had to propagate this change throughout the codebase.

The script will always automatically generate manifest files if no file is detected at the provided `$MANIFEST_FILE_PATH`.

```py
    LIBRISPEECH_TRAIN_NUM = 28539
    LIBRISPEECH_VALID_NUM = 2703
    LIBRISPEECH_TEST_NUM = 2620
    # LIBRISPEECH_PARTS = [
    #     'dev-clean',
    #     'test-clean',
    #     'dev-other',
    #     'test-other',
    #     'train-clean-100',
    #     'train-clean-360',
    #     'train-other-500',
    # ]

    LIBRISPEECH_PARTS = [
        'dev-clean',
        'test-clean',
        'train-clean-100'
    ]
```
