### ISSUE TITLE
학습 완료된 모델을 불러와 하나의 음성 파일을 예측하고 싶습니다

### ISSUE THREAD

**Issue by youngchannelforyou** [openspeech-team/openspeech#205]
# ❓ Questions & Help
현재 학습 완료된 모델을 불러와 하나의 음성 파일을 예측하고 싶습니다. 패키지 내에 함수들은 다량의 데이터 셋으로 테스트하는 것 같아서요!... 이것저것 보면서 짜고 있는데 계속 에러가나 이렇게 질문드립니다.... 혹시 wav 파일 하나만 가지고 테스트해 해당 예측된 말 소리 텍스트를 볼 수 있을까요? 패키지 내에 어느 부분을 참고하면 될까요?... 죄송합니다

## Details

소스코드입니다.

def hydra_main(configs: DictConfig) -> None:

use_cuda = configs.eval.use_cuda and torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")

    tokenizer = TOKENIZER_REGISTRY[configs.tokenizer.unit](configs)

    model = MODEL_REGISTRY[configs.model.model_name]
    model = model.load_from_checkpoint(
        configs.eval.checkpoint_path, configs=configs, tokenizer=tokenizer
    )
    model.to(device)

    audio_path = "/home/net/바탕화면/tool/sample/test.wav"
    mel_spectrogram, sample_rate = load_audio_features(audio_path)

    input_tensor = torch.tensor(mel_spectrogram).unsqueeze(0).to(device)

    input_lengths = torch.tensor([mel_spectrogram.shape[2]]).to(
        device
    )  # Use shape[2] for the sequence length

    with torch.no_grad():
        # Get the encoder outputs from the model
        encoder_outputs, encoder_logits, encoder_output_lengths = model.encoder(
            input_tensor, input_lengths=input_lengths
        )

    predicted_tokens = encoder_outputs["predictions"][0].tolist()
    predicted_sentence = tokenizer.decode(predicted_tokens)

    print(f"Predicted Sentence: {predicted_sentence}")

에러출력본 입니다.

2023-08-01 15:17:30.008978: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-01 15:17:30.029165: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/net/바탕화면/tool/tool_stt_test.py:61: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input_tensor = torch.tensor(mel_spectrogram).unsqueeze(0).to(device)
Traceback (most recent call last):
  File "/home/net/바탕화면/tool/tool_stt_test.py", line 172, in <module>
    hydra_main(configs)
  File "/home/net/바탕화면/tool/tool_stt_test.py", line 70, in hydra_main
    encoder_outputs, encoder_logits, encoder_output_lengths = model.encoder(
  File "/home/net/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/net/바탕화면/tool/openspeech/encoders/lstm_encoder.py", line 122, in forward
    outputs, hidden_states = self.rnn(conv_outputs)
  File "/home/net/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/net/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 810, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/net/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 730, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/net/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 214, in check_input
    raise RuntimeError(
RuntimeError: input must have 2 dimensions, got 3

**Comment by DevTae** [comment]
@youngchannelforyou #162 issue 에 해당 내용에 대하여 다룬 코드가 있습니다!
