### ISSUE TITLE
hydra_train 실행시, 아래와 같은 오류가 발생합니다.

### ISSUE THREAD

**Issue by ChoDaehi** [openspeech-team/openspeech#77]
/Volumes/MacOS/PycharmProjects/openspeech/venv/bin/python /Volumes/MacOS/PycharmProjects/openspeech/openspeech/openspeech_cli/hydra_train.py dataset=librispeech; dataset.dataset_download=True; dataset.dataset_path=$DATASET_PATH; dataset.manifest_file_path=$MANIFEST_FILE_PATH; tokenizer=libri_subword; model=conformer_lstm; audio=fbank; lr_scheduler=warmup_reduce_lr_on_plateau; trainer=cpu; criterion=cross_entropy
Traceback (most recent call last):
  File "/Volumes/MacOS/PycharmProjects/openspeech/openspeech/openspeech_cli/hydra_train.py", line 60, in <module>
    hydra_main()
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
    overrides=args.overrides,
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 91, in run
    run_mode=RunMode.RUN,
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 568, in compose_config
    from_shell=from_shell,
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 231, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/Volumes/MacOS/PycharmProjects/openspeech/venv/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: LexerNoViableAltException: dataset=librispeech;
                                              ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Process finished with exit code 1

**Comment by wl-junlin** [comment]
OverrideParseException，you need to past your train params

**Comment by sooftware** [comment]
실행한 커맨드를 포함해서 알려주실래요? 환경도요.

**Comment by ChoDaehi** [comment]
python hydra_train.py dataset=librispeech; dataset.dataset_download=True; dataset.dataset_path=$DATASET_PATH; dataset.manifest_file_path=$MANIFEST_FILE_PATH; tokenizer=libri_subword; model=conformer_lstm; audio=fbank; lr_scheduler=warmup_reduce_lr_on_plateau; trainer=cpu; criterion=cross_entropy

이걸 macOS Monterey상 virtual env에서 실행했고요. IDE는 PyCharm를 사용하고요.

**Comment by sooftware** [comment]
@ChoDaehi $DATASET_PATH, $MANIFEST_FILE_PATH을 적절하게 설정해줬나요?

**Comment by sooftware** [comment]
이건 코드 에러가 아니라 트레이닝 커맨드 문법 오류입니다. 확인해주세요.
